name: camera.ui
version: 0.1.9
slug: camera_ui
description: Self-hosted NVR and camera management with a modern UI
url: https://github.com/cameraui/homeassistant-apps
image: ghcr.io/cameraui/homeassistant-app-{arch}
arch:
  - amd64
  - aarch64
init: false
host_network: true
homeassistant_api: true
ingress: true
ingress_port: 3080
ingress_stream: true
panel_icon: mdi:cctv
panel_title: camera.ui
environment:
  CAMERA_UI_INSECURE_PORT: "3080"
  CAMERA_UI_INGRESS_TRUST: "172.30.32.2"
map:
  - media:rw
backup_exclude:
  - server
  - python
  - plugins
usb: true
uart: true
gpio: true
video: true
devices:
  - /dev/dri/renderD128
  - /dev/dri/renderD129
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/accel/accel0
  - /dev/kfd
  - /dev/apex_0
  - /dev/apex_1
  - /dev/apex_2
  - /dev/apex_3
  - /dev/hailo0
  - /dev/vchiq
  - /dev/video0
  - /dev/video10
  - /dev/video11
  - /dev/video12
privileged:
  - PERFMON
options:
  default_plugins: "@camera.ui/camera-ui-nvr"
  recordings_path: /media/camera.ui
  internal_avahi: true
schema:
  default_plugins: str
  recordings_path: str
  internal_avahi: bool
